### ISSUE TITLE
The Quckstart examples for local run seem outdated - md.vl doesn't accept (model="path") ?

### ISSUE THREAD

**Issue by Twenkid** [m87-labs/moondream#273]
Hi, I'm trying out running Moondream locally via the module/not hf transformers and I succeeded with 0.0.5, but the out-of-the-box examples from: https://docs.moondream.ai/quick-start  

if following:

```pip install moondream``` (and ```!pip install moondream in Colab)``` are installing the newer 0.1.0 (printed as 1.0.0), where ```md.vl(...)``` doesn't "like" the arguments: (model=path_to_model) ... 

This way works with 0.0.5 as in Readme.md (see the Pull request for updating an explicit requirement for onnxruntime==1.19.2 
:  https://github.com/vikhyat/moondream/pull/272 )

```python
import moondream as md
from PIL import Image

model = md.vl(model='./moondream-0_5b-int4.mf.gz')  # Initialize model
image = Image.open("./path/to/image.jpg")  # Load image
encoded_image = model.encode_image(image)  # Encode image (recommended for multiple operations)

# 1. Caption any image (length options: "short" or "normal" (default))
caption = model.caption(encoded_image)["caption"]
print("Caption:", caption)
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-5-25469824746a>](https://localhost:8080/#) in <cell line: 0>()
      2 from PIL import Image
      3 
----> 4 model = md.vl(model='./moondream-0_5b-int4.mf.gz')  # Initialize model
      5 p = "/content/BRL61-0905.jpg"
      6 image = Image.open(p)  # Load image

[/usr/local/lib/python3.11/dist-packages/moondream/__init__.py](https://localhost:8080/#) in vl(api_key, endpoint, **kwargs)
     22         An instance of CloudVL.
     23     """
---> 24     return CloudVL(api_key=api_key, endpoint=endpoint, **kwargs)
     25 
     26 
```

[I don't if there's also a Colab related error, but the help shows there's no such parameter either:]

**TypeError: CloudVL.__init__() got an unexpected keyword argument 'model'**

```python
print(md.__version__); help(md.vl)
1.0.0
Help on function vl in module moondream:

vl(api_key: Optional[str] = None, endpoint: Optional[str] = 'https://api.moondream.ai/v1', **kwargs)
    Factory function for creating a visual language model client.
    
    Args:
        api_key (str): Your API key for the remote (cloud) API.
        endpoint (str): The endpoint which you would like to call. Local is http://localhost:2020/v1 by default.
        **kwargs.
    
    Returns:
        An instance of CloudVL.

```

https://colab.research.google.com/drive/1nSg6W70NxZ4X6__SOgh5ePcB_PT3IR17?usp=sharing

**Comment by azinudinachzab** [comment]
same here

**Comment by EthanReid** [comment]
Thank you for the feedback, we have changed how the library works behind the scenes and are no longer supporting ONNX. Now it accepts an API endpoint or key. To run locally I would checkout [Moondream Server](https://moondream.ai/moondream-server). Additionally, we have a [Hugging Face Transformers implementation](https://huggingface.co/vikhyatk/moondream2).

**Comment by ahmedosman2001** [comment]
> Thank you for the feedback, we have changed how the library works behind the scenes and are no longer supporting ONNX. Now it accepts an API endpoint or key. To run locally I would checkout [Moondream Server](https://moondream.ai/moondream-server). Additionally, we have a [Hugging Face Transformers implementation](https://huggingface.co/vikhyatk/moondream2).

Thanks for the Info. I’ve been searching for a solution. Could you please update the readme for future users?
Also, if the method above doesn’t work anymore, how can we now use the 0.5B model?
